# Generated by Django 4.0.3 on 2022-03-28 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_avatar_of_choice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar_of_choice',
            name='usr',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chosen_avatar', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
