# Generated by Django 4.0.3 on 2022-03-30 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_avatar_of_choice_usr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portrait', models.ImageField(upload_to='user_images/')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
