# Generated by Django 4.0.3 on 2022-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_character_armour_class_character_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attrib_wisdom',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
