# Generated by Django 4.0.3 on 2022-03-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_character_attrib_wisdom'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='chr_class',
            field=models.CharField(max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
