# Generated by Django 4.0.3 on 2022-03-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_character_chr_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='chr_class',
            field=models.CharField(max_length=13, null=b'I01\n'),
        ),
    ]
