# Generated by Django 4.0.3 on 2022-03-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_character_chr_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='armour_class',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attack',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attention',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_agility',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_charisma',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_endurance',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_intelligence',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_strength',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='attrib_wisdom',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='chr_class',
            field=models.CharField(blank=b'I01\n', max_length=13, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='damage',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='dc_class',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='diety',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='save_reflex',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='save_resilience',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='save_will',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_acrobatics',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_arcane',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_athletics',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_craft',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_decieve',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_diplomacy',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_intimidation',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_medicine',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_nature',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_occult',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_performance',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_religion',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_social',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_stealth',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_survival',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills_theft',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='worldview',
            field=models.CharField(blank=b'I01\n', max_length=2, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
    ]
